### ISSUE TITLE
Error lazy-loading library module

### ISSUE THREAD

**Issue by dfbaskin** [dfbaskin/lerna-angular-cli-monorepo#2]
For the "four" example, I've compiled an Angular module and I am trying to load it dynamically.  The "three" example is similar and it works, but it is loaded by a direct reference.  Tried all of these variations to load it:

```js
  // None of these options work:
  {
    path: "four",
    //loadChildren: "demo-app-example-four/dist#ExampleFourModule"
    //loadChildren: "../../node_modules/demo-app-example-four/dist#ExampleFourModule"
    //loadChildren: "../../../demo-app-example-four/src/app/modules/example-four/example-four.module#ExampleFourModule"
  },
```

**Comment by dfbaskin** [comment]
Appears to be related to this:
https://github.com/angular/angular-cli/issues/2601

But pulling directly from the `node_modules` or `example_four` paths don't seem to work either.

**Comment by dfbaskin** [comment]
Added a [`work-around`](https://github.com/dfbaskin/lerna-angular-cli-monorepo/tree/work-around) branch that moves the output of `packagr` to a `libs` folder within the main project (within the `src` directory).  This fixes the build errors, but still can't lazy load the library module.  Tried these options:

```
  {
    path: "four",
    //loadChildren: "./libs/demo-app-example-four#ExampleFourModule"
    //loadChildren: "./libs/demo-app-example-four/bundles/demo-app-example-four.umd.js#ExampleFourModule"
    loadChildren: function() {
      return System
        .import('./libs/demo-app-example-four')
        .then(function(module) {
          return module.ExampleFourModule;
        });
    }
  },
```

**Comment by dfbaskin** [comment]
There is this solution, but it requires ejecting from `angular-cli`
https://github.com/brandonroberts/angular-router-loader

**Comment by dfbaskin** [comment]
So the fix was to make the AOT compiler happy using a separate exported function:

```js
export function loadExampleFourModule() {
  return System
    .import('./libs/demo-app-example-four')
    .then(function(module) {
      return module.ExampleFourModule;
    });
}
```

and adding this function to the `loadChildren` property:

```js
  {
    path: "four",
    loadChildren: loadExampleFourModule
    // // This syntax breaks the AOT compiler:
    // loadChildren: function loadExampleFourModule() {
    //   return System
    //     .import('./libs/demo-app-example-four')
    //     .then(function(module) {
    //       return module.ExampleFourModule;
    //     });
    // }
  },
```

**Comment by mnicic** [comment]
Is your module `'./libs/demo-app-example-four'` chunk (compiled part of the app in separate file) or completely separate npm package?
Since I'm trying to load Angular module from separate npm package but without success.
